name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Display directory content
        run: ls -R

      - name: Show npm version
        run: npm --version

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: echo "No tests specified"

      - name: Build Docker image
        run: |
          docker build -t image1:latest .
          echo ${{ secrets.AWS_ACCESS_KEY_ID }} | docker login --username AWS --password-stdin 265072753329.dkr.ecr.eu-central-1.amazonaws.com
          docker tag image1:latest 265072753329.dkr.ecr.eu-central-1.amazonaws.com/distributed:image1
          docker push 265072753329.dkr.ecr.eu-central-1.amazonaws.com/distributed:image1
        env:
          AWS_REGION: eu-central-1
